# Generated by Django 3.2.6 on 2021-08-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_commentary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='stars',
            field=models.CharField(max_length=1),
        ),
    ]
